### ISSUE TITLE
Smart store registration failure

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-iOS#2353]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App:Hybrid App
3. OS Version: Android and iOS both
4. Device: iPhone/iPad, Android Phone/Tablet
5. Steps to reproduce: Fresh install after login. 
6. Actual behavior: Smart store registration fails cause due to that app needs to reset session information via login again, after log in again app app launches. Some time it takes 2-3 times. 
7. Expected Behavior: App is supposed to launch successfully
8. Error Log:
`12-20 04:13:59.077 6923-7101/com.mycompany.MyApp I/ForcePlugin: SmartStorePlugin.execute, action: pgRegisterSoup, jsVersion: 5.3.0
12-20 04:13:59.098 6923-7101/com.mycompany.MyApp D/SmartStorePlugin: Main thread time for pgRegisterSoup -> 12
12-20 04:13:59.101 6923-7107/com.mycompany.MyApp E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                    at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                                    at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                                    at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                                    at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
                                                                    at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
                                                                    at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
                                                                    at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
                                                                    at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
                                                                    at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
                                                                    at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
                                                                    at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
                                                                    at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
                                                                    at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                                                                    at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
                                                                    at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:232)
                                                                    at com.salesforce.androidsdk.smartstore.store.SmartStore.registerSoupWithSpec(SmartStore.java:308)
                                                                    at com.salesforce.androidsdk.smartstore.store.SmartStore.registerSoup(SmartStore.java:295)
                                                                    at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.registerSoup(SmartStorePlugin.java:458)
                                                                    at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$800(SmartStorePlugin.java:79)
                                                                    at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:154)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                    at java.lang.Thread.run(Thread.java:764)
12-20 04:13:59.115 6923-7101/com.mycompany.MyApp W/PluginManager: THREAD WARNING: exec() call to com.salesforce.smartstore.pgRegisterSoup blocked the main thread for 45ms. Plugin should use CordovaInterface.getThreadPool().
12-20 04:13:59.121 6923-7107/com.mycompany.MyApp W/SmartStorePlugin: execute call failed
                                                                        net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                            at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                                            at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                                            at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                                            at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
                                                                            at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
                                                                            at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
                                                                            at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
                                                                            at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
                                                                            at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
                                                                            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                                                                            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
                                                                            at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:232)
                                                                            at com.salesforce.androidsdk.smartstore.store.SmartStore.registerSoupWithSpec(SmartStore.java:308)
                                                                            at com.salesforce.androidsdk.smartstore.store.SmartStore.registerSoup(SmartStore.java:295)
                                                                            at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.registerSoup(SmartStorePlugin.java:458)
                                                                            at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$800(SmartStorePlugin.java:79)
                                                                            at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:154)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                            at java.lang.Thread.run(Thread.java:764)`

I have also raised the same issue on google plus as well. 
https://plus.google.com/+ManishKumarRocks4ever/posts/HrAHNb5CQhY

As not getting any response so posting here.

Can anyone respond me on that?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@Manish-Kr09 There was an issue with the encryption key in some cases that we resolved recently. Please upgrade to `Mobile SDK 6.0`.
